---
deployment:
  tasks:
    - export DEPLOYPATH=/home/digiiics/aiwills.digilyse.co
    - /bin/cp -R public/. $DEPLOYPATH/public/
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/touch $DEPLOYPATH/tmp/restart.txt
